name: deploy

on:
  push:
    branches: [main]
  repository_dispatch:
    types: deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
      - run: npm install
      - name: Build
      - run: npm run build:devnet
        env:
          CI: false
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "dev.omr95@gmail.com"
          git config --global user.name "Marius Oprea"
          git checkout --orphan gh-pages
          git rm -rf .
          mv build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
